name: test act
on:
  push:

jobs:
  test-act:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        datacenter:
          - site-c
          - site-d
        exclude:
          - datacenter: site-d
            node-version: 14.x
            site: staging
        include:
          - php-version: 5.4
          - datacenter: site-a
            node-version: 10.x
            site: prod
          - datacenter: site-b
            node-version: 12.x
            site: dev
        node-version: [14.x, 16.x]
        site:
          - staging
    steps:
      - name: echo matrix var
        run: |
          echo 'datacenter is ${{ matrix.datacenter }}, node-version is ${{ matrix.node-version }}, site is ${{matrix.site}}, php-version is ${{matrix.php-version}}'