name: test sequential
on:
  push:

jobs:
  test-act:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fruit: [apple, pear]
        animal: [cat, dog]
        include:
          - color: pink
            animal: cat
          - color: green
          - fruit: apple
            shape: circle
          - fruit: banana
          - fruit: banana
            animal: cat
    steps:
      - name: echo matrix var
        run: |
          echo 'fruit is ${{ matrix.fruit }}, animal is ${{ matrix.animal }}, color is ${{matrix.color}}, shape is ${{matrix.shape}}'